<?php 

/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
JHTML::addIncludePath(JPATH_BASE.DS.'components'.DS.'com_jmailunsubscribe'.DS.'helpers');
?>
<?php if ($this->params->get('show_print_icon') || $this->params->get('show_email_icon')) : ?>
<table class="contentpaneopen<?php echo $this->params->get( 'pageclass_sfx' ); ?>">
<tr>
	<?php if (!$this->print) : ?>
		
		<?php if ( $this->params->get( 'show_print_icon' )) : ?>
		<td align="right" width="100%" class="buttonheading">
		<?php echo JHTML::_('icon.print_popup',  $this->categories, $this->params, NULL, array('view'=>'categories')); ?>
		</td>
		<?php endif; ?>

		<?php if ($this->params->get('show_email_icon')) : ?>
		<td align="right" width="100%" class="buttonheading">
		<?php echo JHTML::_('icon.email',  $this->categories, $this->params, NULL, array('view'=>'categories')); ?>
		</td>
		<?php endif; ?>
		
	<?php else : ?>
		<td align="right" width="100%" class="buttonheading">
		<?php echo JHTML::_('icon.print_screen',  $this->categories, $this->params, NULL, array('view'=>'categories')); ?>
		</td>
	<?php endif; ?>
</tr>
</table>
<?php endif; ?>
<?php if ( $this->params->def( 'show_page_title', 1 ) ) : ?>
<div class="componentheading<?php echo $this->params->get( 'pageclass_sfx' ); ?>">
	<?php echo $this->escape($this->params->get('page_title')); ?>
</div>
<?php endif; ?>
<?php if ( ($this->params->def('image', -1) != -1) || $this->params->def('show_comp_description', 1) ) : ?>
<table width="100%" cellpadding="4" cellspacing="0" border="0" align="center" class="contentpane<?php echo $this->params->get( 'pageclass_sfx' ); ?>">
	<tr>
		<td valign="top" class="contentdescription<?php echo $this->params->get( 'pageclass_sfx' ); ?>">
<?php
  if ( isset($this->image) ) : echo $this->image; endif;
  echo $this->params->get('comp_description');
  ?>
		</td>
	</tr>
</table>
<?php endif; ?>
<ul>
	<?php foreach ( $this->categories as $category ) : ?>
		<li>
			<a href="<?php echo $category->link; ?>" class="category<?php echo $this->params->get( 'pageclass_sfx' ); ?>"><?php echo $this->escape($category->title);?></a>
			<span class="small">
  			(<?php echo $category->numlinks;?>)
			</span>
		</li>
<?php endforeach; ?>
</ul>