<?php 
/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
JHTML::addIncludePath(JPATH_BASE.DS.'components'.DS.'com_jmailunsubscribe'.DS.'helpers');
// uncomment to add custom css file for this view,
// save the css file to media/com_jmailunsubscribe/css/yourcss.css
//use media/com_jmailunsubscribe folder to store your css,js,images,...
//$document =& JFactory::getDocument();
//$document->addStyleSheet($this->baseurl.'/media/com_jmailunsubscribe/css/yourcss.css');
?>
<?php if ($this->params->get('show_print_icon') || $this->params->get('show_email_icon')) : ?>
<table class="contentpaneopen<?php echo $this->params->get( 'pageclass_sfx' ); ?>">
<tr>
	<?php if (!$this->print) : ?>
		
		<?php if ( $this->params->get( 'show_print_icon' )) : ?>
		<td align="right" width="100%" class="buttonheading">
		<?php echo JHTML::_('icon.print_popup',  $this->item, $this->params, NULL, array('view'=>'item')); ?>
		</td>
		<?php endif; ?>

		<?php if ($this->params->get('show_email_icon')) : ?>
		<td align="right" width="100%" class="buttonheading">
		<?php echo JHTML::_('icon.email',  $this->item, $this->params, NULL, array('view'=>'item')); ?>
		</td>
		<?php endif; ?>
		
	<?php else : ?>
		<td align="right" width="100%" class="buttonheading">
		<?php echo JHTML::_('icon.print_screen',  $this->item, $this->params, NULL, array('view'=>'item')); ?>
		</td>
	<?php endif; ?>
</tr>
</table>
<?php endif; ?>

<?php if ( $this->params->def( 'show_page_title', 1 ) ) : ?>
	<h1 class="componentheading<?php echo $this->params->get( 'pageclass_sfx' ); ?>">
	<?php echo $this->escape($this->params->get('page_title')); ?>
	</h1>
<?php endif; ?>

<?php if( $this->params->get('show_date') && $this->item->date ):?>
	<h3>Date</h3>
	<?php echo $this->item->date; ?>
<?php endif; ?>

<?php if (($this->params->get('show_author'))) : ?>
	<p class="small">
		<?php echo JText::_( 'Written by' ); ?>:<?php echo $this->item->created_by_alias; ?>
	</p>
<?php endif; ?>
		
<?php if ($this->params->get('show_create_date')) : ?>
		<p class="small">
		<?php echo JHTML::_('date', $this->item->created, JText::_('DATE_FORMAT_LC2')) ?>
		</p>
<?php endif; ?>

<?php if ( intval($this->item->modified) !=0 && $this->params->get('show_modify_date')) : ?>
	<p class="small">
	<?php echo JText::sprintf('LAST_UPDATED2', JHTML::_('date', $this->item->modified, JText::_('DATE_FORMAT_LC2'))); ?>
	</p>
<?php endif; ?>
		
<?php if ($this->params->get('show_hits')) : ?>
	<p class="small">
	<?php echo JText::_( 'Hits' ); ?>:<?php echo $this->item->hits; ?>
	</p>
<?php endif; ?>

<?php if( $this->item->alertid ):?>
<h3>Alertid</h3>
<?php echo $this->item->alertid; ?>
<?php endif; ?>
<?php if( $this->item->subscribed ):?>
<h3>Subscribed</h3>
<?php echo $this->item->subscribed; ?>
<?php endif; ?>
<?php if( $this->item->pluginssubscribedto ):?>
<h3>Pluginssubscribedto</h3>
<?php echo $this->item->pluginssubscribedto; ?>
<?php endif; ?>
